// src/app/components/projects/projects.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ArrowTopRightIconComponent } from '../shared/icons/arrow-top-right-icon/arrow-top-right-icon.component';
import { GithubLogoIconComponent } from '../shared/icons/github-logo-icon/github-logo-icon.component';

interface Project {
  title: string;
  description: string;
  url?: string;
  repoUrl?: string;
  hardSkills: { title: string; skills: { title: string; url?: string }[] }[];
}

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, ArrowTopRightIconComponent, GithubLogoIconComponent],
  templateUrl: './projects.component.html',
  styles: [],
})
export class ProjectsComponent {
  projects: Project[] = [
    {
      title: 'Chatto',
      url: 'https://chatto.cesarclarosns.com',
      repoUrl: 'https://github.com/cesarclarosns/chatto',
      description: `Chat virtual aleatorio, así es, parecido a Omegle, con la diferencia de que podrás tener listas de amigos y la opción de filtrar el chat virtual para poder conversar con algún tipo de persona, por ejemplo, con algún trastorno del habla.`,
      hardSkills: [
        {
          title: 'Lenguajes',
          skills: [
            {
              title: 'Node/TypeScript',
            },
          ],
        },
        {
          title: 'Frameworks',
          skills: [
            {
              title: 'Angular',
            },
            {
              title: 'NestJS',
            },
          ],
        },
        {
          title: 'Base de datos',
          skills: [
            {
              title: 'PostgreSQL (TimescaleDB)',
            },
          ],
        },
        {
          title: 'Herramientas de CI/CD',
          skills: [
            {
              title: 'GitHub',
            },
            {
              title: 'GitHub Actions',
            },
            {
              title: 'Watchtower (Docker)',
            },
          ],
        },
        {
          title: 'Servicios de AWS',
          skills: [
            {
              title: 'EC2',
            },
            {
              title: 'S3',
            },
            {
              title: 'SES',
            },
            {
              title: 'Route53',
            },
          ],
        },
        {
          title: 'Otras tecnologías y herramientas',
          skills: [
            {
              title: 'Docker',
            },
            {
              title: 'LiveKit',
            },
            {
              title: 'Traefik',
            },
            {
              title: 'Stripe',
            },
          ],
        },
      ],
    },
    {
      title: 'Splendor Clothing',
      url: 'https://splendorclothing.cesarclarosns.com',
      repoUrl: 'https://github.com/cesarclarosns/splendor-clothing',
      description: `E-commerce de moda.`,
      hardSkills: [
        {
          title: 'Lenguajes',
          skills: [
            {
              title: 'Node/JavaScript',
            },
          ],
        },
        {
          title: 'Frameworks',
          skills: [
            {
              title: 'React',
            },
            {
              title: 'Express',
            },
          ],
        },
        {
          title: 'Base de datos',
          skills: [
            {
              title: 'Firebase (Firestore)',
            },
          ],
        },
        {
          title: 'Herramientas de CI/CD',
          skills: [
            {
              title: 'GitHub',
            },
            {
              title: 'GitHub Actions',
            },
            {
              title: 'Watchtower (Docker)',
            },
          ],
        },
        {
          title: 'Servicios de AWS',
          skills: [
            {
              title: 'EC2',
            },
            {
              title: 'Route53',
            },
          ],
        },
        {
          title: 'Otras tecnologías y herramientas',
          skills: [
            {
              title: 'Docker',
            },
            {
              title: 'Traefik',
            },
            {
              title: 'Firebase',
            },
            {
              title: 'Stripe',
            },
          ],
        },
      ],
    },
  ];
}

<section id="projects" class="scroll-mt-40">
  <h1 class="font-bold">PROYECTOS</h1>

  <div class="flex flex-col gap-10 my-4">
    <div
      *ngFor="let project of projects"
      class="flex flex-col gap-4 hover:bg-base-content/10 rounded-xl drop-shadow-lg p-5 opacity-80"
    >
      <div>
        <div class="flex flex-row items-center gap-2">
          <span class="font-bold">{{ project.title }}</span>
          <a [href]="project.url" target="_blank">
            <app-arrow-top-right-icon
              class="h-5 hover:cursor-pointer hover:text-secondary-focus"
            ></app-arrow-top-right-icon>
          </a>
          <a [href]="project.repoUrl" target="_blank">
            <app-github-logo-icon
              class="h-5 hover:cursor-pointer hover:text-secondary-focus"
            ></app-github-logo-icon>
          </a>
        </div>
      </div>

      <div>
        <span>{{ project.description }}</span>
      </div>

      <div class="flex flex-col gap-2">
        <div
          *ngFor="let hardSkill of project.hardSkills"
          class="flex flex-col gap-5"
        >
          <div>
            <p class="font-semibold">{{ hardSkill.title }}:</p>
            <ul class="list-disc pl-5">
              <li
                *ngFor="let skill of hardSkill.skills"
                class="group hover:cursor-pointer hover:text-secondary-focus"
              >
                <a class="transition-all duration-300 ease-in-out">
                  <span
                    class="bg-left-bottom bg-gradient-to-r from-secondary-focus to-secondary-focus bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out"
                  >
                    {{ skill.title }}
                  </span>
                </a>
                &nbsp;&nbsp;
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// client/src/app/projects/page.tsx
"use client";

import Icons from "@/components/ui/icons";
import useRandomColorClass from "@/hooks/use-random-color-class";
import { cn } from "@/lib/utils";
import Link from "next/link";

interface Project {
  title: string;
  repo: string;
  url: string;
  description: string[];
  stack: { title: string; content: string }[];
  status?: "released" | "in-progress";
}

export default function ProjectsPage() {
  const projects: Project[] = [
    {
      title: "Chatto",
      status: "in-progress",
      repo: "https://github.com/cesarclarosns/chatto",
      url: "https://chatto.cesarclarosns.com/",
      description: [
        "Random virtual chat, that's right, similar to Omegle, with the difference that you can have lists of friends and the option to filter the virtual chat to be able to chat with some type of person, for example, with a speech disorder.",
      ],
      stack: [
        {
          title: "Frameworks:",
          content: "Angular and NestJS.",
        },
        {
          title: "Databases:",
          content: "PostgreSQL (TimescaleDB).",
        },
        {
          title: "CI/CD tools:",
          content: "Github, Github Actions and Watchtower (Docker).",
        },
        {
          title: "Cloud:",
          content: "AWS.",
        },
        {
          title: "Other technologies and tools:",
          content: "Docker, LiveKit, Traefik and Stripe.",
        },
      ],
    },
    {
      title: "Splendor Clothing",
      status: "released",
      repo: "https://github.com/cesarclarosns/splendor-clothing",
      url: "https://splendorclothing.cesarclarosns.com/",
      description: ["Clothing e-commerce."],
      stack: [
        {
          title: "Frameworks:",
          content: "React and ExpressJS.",
        },
        {
          title: "Databases:",
          content: "Firebase (Firestore).",
        },
        {
          title: "CI/CD tools:",
          content: "Github, Github Actions and Watchtower (Docker).",
        },
        {
          title: "Cloud:",
          content: "AWS.",
        },
        {
          title: "Other technologies and tools:",
          content: "Docker, Traefik and Stripe.",
        },
      ],
    },
  ];

  const { colorClass } = useRandomColorClass({});

  return (
    <div className={cn("flex min-h-screen flex-col px-5 py-20", colorClass)}>
      <div className="flex flex-col gap-20">
        {projects.map((project, i) => {
          return (
            <>
              <div key={i} className="flex flex-col gap-10 md:flex-row">
                <div className="flex flex-col gap-5 md:basis-1/2">
                  <div>
                    <p>
                      <span className="text-2xl font-bold">
                        {project.title}
                      </span>
                      {"  "}
                      <span>
                        {project.status === "in-progress"
                          ? "(In progress)"
                          : "(Released)"}
                      </span>
                    </p>

                    <div className="flex items-center gap-2 text-2xl font-bold">
                      <Link href={project.url} target="_blank">
                        <Icons.ExternalLinkIcon></Icons.ExternalLinkIcon>
                      </Link>

                      <Link href={project.repo} target="_blank">
                        <Icons.GitHubLogoIcon></Icons.GitHubLogoIcon>
                      </Link>
                    </div>
                  </div>
                  <div className="flex flex-col gap-5">
                    {project.description.map((d, i) => (
                      <div key={i}>
                        <span>{d}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex flex-col gap-10 md:basis-1/2">
                  <div className="flex flex-col gap-5">
                    <p className=" font-bold underline">Stack</p>
                    <div className="flex flex-col gap-2">
                      {project.stack.map((skill, i) => (
                        <div key={i}>
                          <p className="font-medium">{skill.title}</p>
                          <p>{skill.content}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </>
          );
        })}
      </div>
    </div>
  );
}
